### SSL Settings
### If you use SSL certificate, first of all, set ssl setting below true
ssl: false
### then, uncomment ssl_cert and ssl_key
# ssl_cert: /path/to/your/ssl.pem
# ssl_key: /path/to/your/private_key.pem

### Server Settings
### specify host and port that cas server run
host: 127.0.0.1
port: 3000

### GrantingDefaultExpire is seconds from last used for deletion ticket
### This value will be set as second.
### (T|P)GT will expires 7,200s (2 hour) as default.
### If you want to use infinite expire policy, set 0
granting_default_expire: 7200

# Also, TGT will be timed-up in 28,800s (8 hour) from creation
# This parameter also can be infinity when set 0
granting_hard_timeout: 28800

### TicketNumberOfEachUsers is a threshold of tickets that users are allowed to create
### This parameter is enabled only on ST/PT
### Default value is 20
ticket_number_of_each_users: 20

### specify uri_path if you want to change the root path
### cas server will be served
# uri_path: /cas

### Database Setting
### Set up the database connection
### NOTE: This doesn't work correctly yet.
# database:
#   driver: mysql
#   name: casdb
#   user: casuser
#   pass: password
#   host: localhost
#   port: 3306

### Authenticator Setting
### NOTE: This doesn't work correctly yet.
# authenticator:
#   driver: database
#   dbauth:
#     database:
#       driver: mysql
#       name: roledb
#       user: roleuser
#       pass: rolepass
#       host: localhost
#       port: 3306
#     table: users
#     user_name_column: admin
#     password_column: password
### if you use salt for authentication, write your salt-column
#     salt_column: salt
### do you want some custom attributes ? so, configure that
### name is an element's name to output
### column_name is a name to be used when select from db
#     custom_attributes:
#       - name: user_id
#         column_name: id
#       - name: display_name
#         column_name: display_name
#       - name: user_age
#         column_name: age

### Log Setting
### NOTE: This doesn't work correctly yet.
# logging:
#   driver: stdout
#   level: debug
