ssl: false

host: localhost
port: 3000

uri_path: /cas

database:
  driver: mysql
  name: casdb
  user: casuser
  pass: password
  host: localhost
  port: 3306

authenticator:
  driver: database
  database:
    driver: mysql
    name: roledb
    user: roleuser
    pass: rolepass
    host: localhost
    port: 3306

logging:
  driver: file
  file: casserver.log
  level: debug
