ssl: false

host: localhost
port: 3000
organization: Example

uri_path: /cas

database:
  driver: mysql
  name: casdb
  user: casuser
  pass: password
  host: localhost
  port: 3306
  parameters:
    parseTime: true
    loc:       Asia/Tokyo
    charset:   utf8mb4,utf8
    collation: utf8mb4_bin

authenticator:
  driver: database
  dbauth:
    database:
      driver: mysql
      name: roledb
      user: roleuser
      pass: rolepass
      host: localhost
      port: 3306
      parameters:
        parseTime: true
        loc:       Asia/Tokyo
        charset:   utf8mb4,utf8
        collation: utf8mb4_bin
    table: auth
    user_name_column: admin
    password_column: password

logging:
  driver: file
  file: casserver.log
  level: debug
